[build-system]
requires = ["setuptools >= 42", "setuptools_scm >= 6", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build=true
envlist = py38

[testenv]
deps = pytest
commands = pytest tests/
"""
